CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar(100) UNIQUE NOT NULL,
  "email" varchar(255) UNIQUE NOT NULL,
  "password_hash" text NOT NULL,
  "is_host" boolean DEFAULT false,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "properties" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar(255) NOT NULL,
  "description" text,
  "location" varchar(255),
  "price_per_night" numeric(10,2) NOT NULL,
  "host_id" integer NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "bookings" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "property_id" integer NOT NULL,
  "start_date" date NOT NULL,
  "end_date" date NOT NULL,
  "status" varchar(50) NOT NULL,
  "created_at" timestamp DEFAULT (now())
);

CREATE TABLE "payments" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "booking_id" integer UNIQUE NOT NULL,
  "amount" numeric(10,2) NOT NULL,
  "payment_method" varchar(50),
  "status" varchar(50) NOT NULL,
  "paid_at" timestamp
);

CREATE TABLE "reviews" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" integer NOT NULL,
  "property_id" integer NOT NULL,
  "rating" integer,
  "comment" text,
  "created_at" timestamp DEFAULT (now())
);

COMMENT ON COLUMN "bookings"."status" IS 'pending, confirmed, cancelled';

COMMENT ON COLUMN "payments"."status" IS 'success, failed';

COMMENT ON COLUMN "reviews"."rating" IS '1 to 5';

ALTER TABLE "properties" ADD FOREIGN KEY ("host_id") REFERENCES "users" ("id");

ALTER TABLE "bookings" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "bookings" ADD FOREIGN KEY ("property_id") REFERENCES "properties" ("id");

ALTER TABLE "payments" ADD FOREIGN KEY ("booking_id") REFERENCES "bookings" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "reviews" ADD FOREIGN KEY ("property_id") REFERENCES "properties" ("id");
